// Code generated by go-swagger; DO NOT EDIT.

package access_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/soopsio/mgmt/api/v1/models"
)

// CreateAccessKeyCreatedCode is the HTTP code returned for type CreateAccessKeyCreated
const CreateAccessKeyCreatedCode int = 201

/*CreateAccessKeyCreated 无返回值

swagger:response createAccessKeyCreated
*/
type CreateAccessKeyCreated struct {
}

// NewCreateAccessKeyCreated creates CreateAccessKeyCreated with default headers values
func NewCreateAccessKeyCreated() *CreateAccessKeyCreated {
	return &CreateAccessKeyCreated{}
}

// WriteResponse to the client
func (o *CreateAccessKeyCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*CreateAccessKeyDefault Unexpected error

swagger:response createAccessKeyDefault
*/
type CreateAccessKeyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAccessKeyDefault creates CreateAccessKeyDefault with default headers values
func NewCreateAccessKeyDefault(code int) *CreateAccessKeyDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateAccessKeyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create access key default response
func (o *CreateAccessKeyDefault) WithStatusCode(code int) *CreateAccessKeyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create access key default response
func (o *CreateAccessKeyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create access key default response
func (o *CreateAccessKeyDefault) WithPayload(payload *models.Error) *CreateAccessKeyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create access key default response
func (o *CreateAccessKeyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAccessKeyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
