// Code generated by go-swagger; DO NOT EDIT.

package access_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/soopsio/mgmt/api/v1/models"
)

// GetAccessKeyPoliciesOKCode is the HTTP code returned for type GetAccessKeyPoliciesOK
const GetAccessKeyPoliciesOKCode int = 200

/*GetAccessKeyPoliciesOK 返回匹配策略

swagger:response getAccessKeyPoliciesOK
*/
type GetAccessKeyPoliciesOK struct {

	/*
	  In: Body
	*/
	Payload models.Policies `json:"body,omitempty"`
}

// NewGetAccessKeyPoliciesOK creates GetAccessKeyPoliciesOK with default headers values
func NewGetAccessKeyPoliciesOK() *GetAccessKeyPoliciesOK {
	return &GetAccessKeyPoliciesOK{}
}

// WithPayload adds the payload to the get access key policies o k response
func (o *GetAccessKeyPoliciesOK) WithPayload(payload models.Policies) *GetAccessKeyPoliciesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get access key policies o k response
func (o *GetAccessKeyPoliciesOK) SetPayload(payload models.Policies) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccessKeyPoliciesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Policies, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetAccessKeyPoliciesDefault Unexpected error

swagger:response getAccessKeyPoliciesDefault
*/
type GetAccessKeyPoliciesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAccessKeyPoliciesDefault creates GetAccessKeyPoliciesDefault with default headers values
func NewGetAccessKeyPoliciesDefault(code int) *GetAccessKeyPoliciesDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAccessKeyPoliciesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get access key policies default response
func (o *GetAccessKeyPoliciesDefault) WithStatusCode(code int) *GetAccessKeyPoliciesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get access key policies default response
func (o *GetAccessKeyPoliciesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get access key policies default response
func (o *GetAccessKeyPoliciesDefault) WithPayload(payload *models.Error) *GetAccessKeyPoliciesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get access key policies default response
func (o *GetAccessKeyPoliciesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccessKeyPoliciesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
