// Code generated by go-swagger; DO NOT EDIT.

package access_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/soopsio/mgmt/api/v1/models"
)

// GetAccessKeysOKCode is the HTTP code returned for type GetAccessKeysOK
const GetAccessKeysOKCode int = 200

/*GetAccessKeysOK 返回 AccessKey 列表，如果action=generate,则返回只包含一个自动生成的Key元素的数组

swagger:response getAccessKeysOK
*/
type GetAccessKeysOK struct {

	/*
	  In: Body
	*/
	Payload models.AccessKeys `json:"body,omitempty"`
}

// NewGetAccessKeysOK creates GetAccessKeysOK with default headers values
func NewGetAccessKeysOK() *GetAccessKeysOK {
	return &GetAccessKeysOK{}
}

// WithPayload adds the payload to the get access keys o k response
func (o *GetAccessKeysOK) WithPayload(payload models.AccessKeys) *GetAccessKeysOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get access keys o k response
func (o *GetAccessKeysOK) SetPayload(payload models.AccessKeys) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccessKeysOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.AccessKeys, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetAccessKeysDefault Unexpected error

swagger:response getAccessKeysDefault
*/
type GetAccessKeysDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAccessKeysDefault creates GetAccessKeysDefault with default headers values
func NewGetAccessKeysDefault(code int) *GetAccessKeysDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAccessKeysDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get access keys default response
func (o *GetAccessKeysDefault) WithStatusCode(code int) *GetAccessKeysDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get access keys default response
func (o *GetAccessKeysDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get access keys default response
func (o *GetAccessKeysDefault) WithPayload(payload *models.Error) *GetAccessKeysDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get access keys default response
func (o *GetAccessKeysDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccessKeysDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
