// Code generated by go-swagger; DO NOT EDIT.

package access_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAccessKeysHandlerFunc turns a function with the right signature into a get access keys handler
type GetAccessKeysHandlerFunc func(GetAccessKeysParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAccessKeysHandlerFunc) Handle(params GetAccessKeysParams) middleware.Responder {
	return fn(params)
}

// GetAccessKeysHandler interface for that can handle valid get access keys params
type GetAccessKeysHandler interface {
	Handle(GetAccessKeysParams) middleware.Responder
}

// NewGetAccessKeys creates a new http.Handler for the get access keys operation
func NewGetAccessKeys(ctx *middleware.Context, handler GetAccessKeysHandler) *GetAccessKeys {
	return &GetAccessKeys{Context: ctx, Handler: handler}
}

/*GetAccessKeys swagger:route GET /accesskeys AccessKeys getAccessKeys

get AccessKeys

获取用户列表


*/
type GetAccessKeys struct {
	Context *middleware.Context
	Handler GetAccessKeysHandler
}

func (o *GetAccessKeys) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAccessKeysParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
