// Code generated by go-swagger; DO NOT EDIT.

package access_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAccessKeyHandlerFunc turns a function with the right signature into a get access key handler
type GetAccessKeyHandlerFunc func(GetAccessKeyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAccessKeyHandlerFunc) Handle(params GetAccessKeyParams) middleware.Responder {
	return fn(params)
}

// GetAccessKeyHandler interface for that can handle valid get access key params
type GetAccessKeyHandler interface {
	Handle(GetAccessKeyParams) middleware.Responder
}

// NewGetAccessKey creates a new http.Handler for the get access key operation
func NewGetAccessKey(ctx *middleware.Context, handler GetAccessKeyHandler) *GetAccessKey {
	return &GetAccessKey{Context: ctx, Handler: handler}
}

/*GetAccessKey swagger:route GET /accesskeys/{key_id} AccessKeys getAccessKey

get AccessKey

获取用户信息


*/
type GetAccessKey struct {
	Context *middleware.Context
	Handler GetAccessKeyHandler
}

func (o *GetAccessKey) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAccessKeyParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
