// Code generated by go-swagger; DO NOT EDIT.

package access_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAccessKeysParams creates a new GetAccessKeysParams object
// with the default values initialized.
func NewGetAccessKeysParams() GetAccessKeysParams {
	var ()
	return GetAccessKeysParams{}
}

// GetAccessKeysParams contains all the bound params for the get access keys operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAccessKeys
type GetAccessKeysParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	AccessKeyID string
	/*
	  Required: true
	  In: query
	*/
	Signature string
	/*
	  Required: true
	  In: query
	*/
	SignatureMethod string
	/*
	  Required: true
	  In: query
	*/
	SignatureNonce string
	/*
	  Required: true
	  In: query
	*/
	SignatureVersion string
	/*
	  Required: true
	  In: query
	*/
	Timestamp string
	/*
	  Required: true
	  In: query
	*/
	Version string
	/*参数为 generate 时生成 key_id 及 key_secret

	  In: query
	*/
	Action *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetAccessKeysParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qAccessKeyID, qhkAccessKeyID, _ := qs.GetOK("AccessKeyId")
	if err := o.bindAccessKeyID(qAccessKeyID, qhkAccessKeyID, route.Formats); err != nil {
		res = append(res, err)
	}

	qSignature, qhkSignature, _ := qs.GetOK("Signature")
	if err := o.bindSignature(qSignature, qhkSignature, route.Formats); err != nil {
		res = append(res, err)
	}

	qSignatureMethod, qhkSignatureMethod, _ := qs.GetOK("SignatureMethod")
	if err := o.bindSignatureMethod(qSignatureMethod, qhkSignatureMethod, route.Formats); err != nil {
		res = append(res, err)
	}

	qSignatureNonce, qhkSignatureNonce, _ := qs.GetOK("SignatureNonce")
	if err := o.bindSignatureNonce(qSignatureNonce, qhkSignatureNonce, route.Formats); err != nil {
		res = append(res, err)
	}

	qSignatureVersion, qhkSignatureVersion, _ := qs.GetOK("SignatureVersion")
	if err := o.bindSignatureVersion(qSignatureVersion, qhkSignatureVersion, route.Formats); err != nil {
		res = append(res, err)
	}

	qTimestamp, qhkTimestamp, _ := qs.GetOK("Timestamp")
	if err := o.bindTimestamp(qTimestamp, qhkTimestamp, route.Formats); err != nil {
		res = append(res, err)
	}

	qVersion, qhkVersion, _ := qs.GetOK("Version")
	if err := o.bindVersion(qVersion, qhkVersion, route.Formats); err != nil {
		res = append(res, err)
	}

	qAction, qhkAction, _ := qs.GetOK("action")
	if err := o.bindAction(qAction, qhkAction, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAccessKeysParams) bindAccessKeyID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("AccessKeyId", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("AccessKeyId", "query", raw); err != nil {
		return err
	}

	o.AccessKeyID = raw

	return nil
}

func (o *GetAccessKeysParams) bindSignature(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("Signature", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("Signature", "query", raw); err != nil {
		return err
	}

	o.Signature = raw

	return nil
}

func (o *GetAccessKeysParams) bindSignatureMethod(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("SignatureMethod", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("SignatureMethod", "query", raw); err != nil {
		return err
	}

	o.SignatureMethod = raw

	return nil
}

func (o *GetAccessKeysParams) bindSignatureNonce(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("SignatureNonce", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("SignatureNonce", "query", raw); err != nil {
		return err
	}

	o.SignatureNonce = raw

	return nil
}

func (o *GetAccessKeysParams) bindSignatureVersion(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("SignatureVersion", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("SignatureVersion", "query", raw); err != nil {
		return err
	}

	o.SignatureVersion = raw

	return nil
}

func (o *GetAccessKeysParams) bindTimestamp(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("Timestamp", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("Timestamp", "query", raw); err != nil {
		return err
	}

	o.Timestamp = raw

	return nil
}

func (o *GetAccessKeysParams) bindVersion(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("Version", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("Version", "query", raw); err != nil {
		return err
	}

	o.Version = raw

	return nil
}

func (o *GetAccessKeysParams) bindAction(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Action = &raw

	return nil
}
