// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ChildStatus child status
// swagger:model ChildStatus
type ChildStatus map[string]string

// Validate validates this child status
func (m ChildStatus) Validate(formats strfmt.Registry) error {
	return nil
}
