// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ExtraVars extra vars
// swagger:model ExtraVars
type ExtraVars map[string]string

// Validate validates this extra vars
func (m ExtraVars) Validate(formats strfmt.Registry) error {
	return nil
}
