// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// InventoryDatas inventory datas
// swagger:model InventoryDatas
type InventoryDatas map[string]InventoryData

// Validate validates this inventory datas
func (m InventoryDatas) Validate(formats strfmt.Registry) error {
	return nil
}
