// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TaskState task state
// swagger:model TaskState
type TaskState struct {

	// 子任务状态
	Childstatus map[string]ChildStatus `json:"childstatus,omitempty"`

	// 运行状态
	Status string `json:"status,omitempty"`

	// 由machinery生成的taskid
	Taskid string `json:"taskid,omitempty"`

	// 版本号
	Version string `json:"version,omitempty"`
}

// Validate validates this task state
func (m *TaskState) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TaskState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskState) UnmarshalBinary(b []byte) error {
	var res TaskState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
