// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Task task
// swagger:model Task
type Task struct {

	// extra vars
	ExtraVars ExtraVars `json:"extra_vars,omitempty"`

	// inventory
	Inventory InventoryDatas `json:"inventory,omitempty"`

	// 任务类型(ansible modules)，参考 http://docs.ansible.com/ansible/list_of_all_modules.html
	Module string `json:"module,omitempty"`

	// module args
	ModuleArgs string `json:"module_args,omitempty"`

	// playbook
	Playbook string `json:"playbook,omitempty"`

	// 直接执行脚本, 脚本中可以调用playbook
	Script string `json:"script,omitempty"`

	// script args
	ScriptArgs string `json:"script_args,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this task
func (m *Task) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Task) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Task) UnmarshalBinary(b []byte) error {
	var res Task
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
