// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/soopsio/mgmt/api/v1/models"
)

// CreatePolicyCreatedCode is the HTTP code returned for type CreatePolicyCreated
const CreatePolicyCreatedCode int = 201

/*CreatePolicyCreated 无返回值

swagger:response createPolicyCreated
*/
type CreatePolicyCreated struct {
}

// NewCreatePolicyCreated creates CreatePolicyCreated with default headers values
func NewCreatePolicyCreated() *CreatePolicyCreated {
	return &CreatePolicyCreated{}
}

// WriteResponse to the client
func (o *CreatePolicyCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*CreatePolicyDefault Unexpected error

swagger:response createPolicyDefault
*/
type CreatePolicyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreatePolicyDefault creates CreatePolicyDefault with default headers values
func NewCreatePolicyDefault(code int) *CreatePolicyDefault {
	if code <= 0 {
		code = 500
	}

	return &CreatePolicyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create policy default response
func (o *CreatePolicyDefault) WithStatusCode(code int) *CreatePolicyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create policy default response
func (o *CreatePolicyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create policy default response
func (o *CreatePolicyDefault) WithPayload(payload *models.Error) *CreatePolicyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create policy default response
func (o *CreatePolicyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePolicyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
