// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/soopsio/mgmt/api/v1/models"
)

// GetPolicyOKCode is the HTTP code returned for type GetPolicyOK
const GetPolicyOKCode int = 200

/*GetPolicyOK 返回指定策略

swagger:response getPolicyOK
*/
type GetPolicyOK struct {

	/*
	  In: Body
	*/
	Payload *models.Policy `json:"body,omitempty"`
}

// NewGetPolicyOK creates GetPolicyOK with default headers values
func NewGetPolicyOK() *GetPolicyOK {
	return &GetPolicyOK{}
}

// WithPayload adds the payload to the get policy o k response
func (o *GetPolicyOK) WithPayload(payload *models.Policy) *GetPolicyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get policy o k response
func (o *GetPolicyOK) SetPayload(payload *models.Policy) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPolicyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetPolicyDefault Unexpected error

swagger:response getPolicyDefault
*/
type GetPolicyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPolicyDefault creates GetPolicyDefault with default headers values
func NewGetPolicyDefault(code int) *GetPolicyDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPolicyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get policy default response
func (o *GetPolicyDefault) WithStatusCode(code int) *GetPolicyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get policy default response
func (o *GetPolicyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get policy default response
func (o *GetPolicyDefault) WithPayload(payload *models.Error) *GetPolicyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get policy default response
func (o *GetPolicyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPolicyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
