// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Ansilbe API
Ansible 管理接口

Terms Of Service:

http://swagger.io/terms/


    Schemes:
      http
      https
    Host: 172.168.88.88:8080
    BasePath: /api/v1
    Version: 1.0.0
    License: Creative Commons 4.0 International http://creativecommons.org/licenses/by/4.0/
    Contact: Swagger API Team http://swagger.io

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
