// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Ansible 管理接口",
    "title": "Ansilbe API",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "name": "Swagger API Team",
      "url": "http://swagger.io"
    },
    "license": {
      "name": "Creative Commons 4.0 International",
      "url": "http://creativecommons.org/licenses/by/4.0/"
    },
    "version": "1.0.0"
  },
  "host": "172.168.88.88:8080",
  "basePath": "/api/v1",
  "paths": {
    "/accesskeys": {
      "get": {
        "description": "获取用户列表\n",
        "tags": [
          "AccessKeys"
        ],
        "summary": "get AccessKeys",
        "operationId": "getAccessKeys",
        "security": null,
        "parameters": [
          {
            "type": "string",
            "description": "参数为 generate 时生成 key_id 及 key_secret\n",
            "name": "action",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "返回 AccessKey 列表，如果action=generate,则返回只包含一个自动生成的Key元素的数组",
            "schema": {
              "$ref": "#/definitions/AccessKeys"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "新增用户\n",
        "tags": [
          "AccessKeys"
        ],
        "summary": "create AccessKey",
        "operationId": "createAccessKey",
        "security": null,
        "parameters": [
          {
            "name": "access_key",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AccessKey"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "无返回值"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/Version"
        },
        {
          "$ref": "#/parameters/AccessKeyId"
        },
        {
          "$ref": "#/parameters/SignatureMethod"
        },
        {
          "$ref": "#/parameters/SignatureVersion"
        },
        {
          "$ref": "#/parameters/SignatureNonce"
        },
        {
          "$ref": "#/parameters/Timestamp"
        },
        {
          "$ref": "#/parameters/Signature"
        }
      ]
    },
    "/accesskeys/{key_id}": {
      "get": {
        "description": "获取用户信息\n",
        "tags": [
          "AccessKeys"
        ],
        "summary": "get AccessKey",
        "operationId": "getAccessKey",
        "security": null,
        "parameters": [
          {
            "type": "string",
            "name": "key_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "返回 AccessKey",
            "schema": {
              "$ref": "#/definitions/AccessKey"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "获取用户信息\n",
        "tags": [
          "AccessKeys"
        ],
        "summary": "delete AccessKey",
        "operationId": "deleteAccessKey",
        "security": null,
        "parameters": [
          {
            "type": "string",
            "name": "key_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "无返回值"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/Version"
        },
        {
          "$ref": "#/parameters/AccessKeyId"
        },
        {
          "$ref": "#/parameters/SignatureMethod"
        },
        {
          "$ref": "#/parameters/SignatureVersion"
        },
        {
          "$ref": "#/parameters/SignatureNonce"
        },
        {
          "$ref": "#/parameters/Timestamp"
        },
        {
          "$ref": "#/parameters/Signature"
        }
      ]
    },
    "/accesskeys/{key_id}/policies": {
      "get": {
        "description": "获取指定 access_key_id 匹配的策略\n",
        "tags": [
          "AccessKeys"
        ],
        "summary": "get Policy",
        "operationId": "getAccessKeyPolicies",
        "security": null,
        "parameters": [
          {
            "type": "string",
            "name": "key_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "返回匹配策略",
            "schema": {
              "$ref": "#/definitions/Policies"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/Version"
        },
        {
          "$ref": "#/parameters/AccessKeyId"
        },
        {
          "$ref": "#/parameters/SignatureMethod"
        },
        {
          "$ref": "#/parameters/SignatureVersion"
        },
        {
          "$ref": "#/parameters/SignatureNonce"
        },
        {
          "$ref": "#/parameters/Timestamp"
        },
        {
          "$ref": "#/parameters/Signature"
        }
      ]
    },
    "/policies": {
      "post": {
        "description": "新增IAM策略\n",
        "tags": [
          "Policies"
        ],
        "summary": "put Policy",
        "operationId": "createPolicy",
        "security": null,
        "parameters": [
          {
            "name": "policy_data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Policy"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "无返回值"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/Version"
        },
        {
          "$ref": "#/parameters/AccessKeyId"
        },
        {
          "$ref": "#/parameters/SignatureMethod"
        },
        {
          "$ref": "#/parameters/SignatureVersion"
        },
        {
          "$ref": "#/parameters/SignatureNonce"
        },
        {
          "$ref": "#/parameters/Timestamp"
        },
        {
          "$ref": "#/parameters/Signature"
        }
      ]
    },
    "/policies/{id}": {
      "get": {
        "description": "获取IAM策略\n",
        "tags": [
          "Policies"
        ],
        "summary": "get Policy",
        "operationId": "getPolicy",
        "security": null,
        "responses": {
          "200": {
            "description": "返回指定策略",
            "schema": {
              "$ref": "#/definitions/Policy"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "删除IAM策略\n",
        "tags": [
          "Policies"
        ],
        "summary": "get Policy",
        "operationId": "delPolicy",
        "security": null,
        "responses": {
          "201": {
            "description": "无返回值"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/Version"
        },
        {
          "$ref": "#/parameters/AccessKeyId"
        },
        {
          "$ref": "#/parameters/SignatureMethod"
        },
        {
          "$ref": "#/parameters/SignatureVersion"
        },
        {
          "$ref": "#/parameters/SignatureNonce"
        },
        {
          "$ref": "#/parameters/Timestamp"
        },
        {
          "$ref": "#/parameters/Signature"
        },
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/tasks": {
      "get": {
        "description": "获取任务状态\n",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "Tasks"
        ],
        "summary": "Get Task",
        "operationId": "getTasks",
        "security": null,
        "responses": {
          "200": {
            "description": "返回TaskIDs state",
            "schema": {
              "$ref": "#/definitions/TaskStates"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "创建任务\n",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "Tasks"
        ],
        "summary": "Create Task",
        "operationId": "createTask",
        "security": null,
        "parameters": [
          {
            "name": "task",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Task"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "返回TaskID",
            "schema": {
              "$ref": "#/definitions/TaskState"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/Version"
        },
        {
          "$ref": "#/parameters/AccessKeyId"
        },
        {
          "$ref": "#/parameters/SignatureMethod"
        },
        {
          "$ref": "#/parameters/SignatureVersion"
        },
        {
          "$ref": "#/parameters/SignatureNonce"
        },
        {
          "$ref": "#/parameters/Timestamp"
        },
        {
          "$ref": "#/parameters/Signature"
        }
      ]
    },
    "/tasks/{task_id}": {
      "get": {
        "description": "获取任务状态\n",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "Tasks"
        ],
        "summary": "Get Task",
        "operationId": "getTask",
        "security": null,
        "responses": {
          "200": {
            "description": "返回TaskID",
            "schema": {
              "$ref": "#/definitions/TaskState"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "修改任务\n",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "Tasks"
        ],
        "summary": "delete Task",
        "operationId": "deleteTask",
        "security": null,
        "parameters": [
          {
            "type": "string",
            "description": "-\u003e| action=stop 时停止任务",
            "name": "action",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "无返回值"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/Version"
        },
        {
          "$ref": "#/parameters/AccessKeyId"
        },
        {
          "$ref": "#/parameters/SignatureMethod"
        },
        {
          "$ref": "#/parameters/SignatureVersion"
        },
        {
          "$ref": "#/parameters/SignatureNonce"
        },
        {
          "$ref": "#/parameters/Timestamp"
        },
        {
          "$ref": "#/parameters/Signature"
        },
        {
          "type": "string",
          "description": "Taskid",
          "name": "task_id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "AccessKey": {
      "type": "object",
      "properties": {
        "Comment": {
          "type": "string"
        },
        "IsAdmin": {
          "type": "integer",
          "format": "int32"
        },
        "KeyId": {
          "type": "string"
        },
        "KeySecret": {
          "type": "string"
        },
        "NickName": {
          "type": "string"
        }
      }
    },
    "AccessKeys": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/AccessKey"
      }
    },
    "ChildStatus": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "ExtraVars": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "InventoryData": {
      "type": "object",
      "additionalProperties": {
        "allOf": [
          {
            "additionalProperties": {
              "type": "object"
            }
          },
          {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        ]
      }
    },
    "InventoryDatas": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/InventoryData"
      }
    },
    "Policies": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Policy"
      }
    },
    "Policy": {
      "type": "object",
      "properties": {
        "actions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "conditions": {
          "$ref": "#/definitions/conditions"
        },
        "description": {
          "type": "string"
        },
        "effect": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "resources": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "subjects": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "Task": {
      "type": "object",
      "properties": {
        "extra_vars": {
          "$ref": "#/definitions/ExtraVars"
        },
        "inventory": {
          "$ref": "#/definitions/InventoryDatas"
        },
        "module": {
          "description": "任务类型(ansible modules)，参考 http://docs.ansible.com/ansible/list_of_all_modules.html",
          "type": "string",
          "example": "raw"
        },
        "module_args": {
          "type": "string",
          "example": "uptime"
        },
        "playbook": {
          "type": "string",
          "example": "/root/ping.yml"
        },
        "script": {
          "description": "直接执行脚本, 脚本中可以调用playbook ",
          "type": "string",
          "example": "raw"
        },
        "script_args": {
          "type": "string",
          "example": "-a aaa -b bbb -c"
        },
        "type": {
          "type": "string",
          "example": "playbook|module|script"
        }
      }
    },
    "TaskState": {
      "type": "object",
      "properties": {
        "childstatus": {
          "description": "子任务状态",
          "additionalProperties": {
            "$ref": "#/definitions/ChildStatus"
          }
        },
        "status": {
          "description": "运行状态",
          "type": "string"
        },
        "taskid": {
          "description": "由machinery生成的taskid",
          "type": "string"
        },
        "version": {
          "description": "版本号",
          "type": "string"
        }
      }
    },
    "TaskStates": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/TaskState"
      }
    },
    "condition": {
      "properties": {
        "options": {
          "$ref": "#/definitions/condition_options"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "condition_options": {
      "additionalProperties": {
        "type": "string"
      }
    },
    "conditions": {
      "additionalProperties": {
        "$ref": "#/definitions/condition"
      }
    }
  },
  "parameters": {
    "AccessKeyId": {
      "type": "string",
      "name": "AccessKeyId",
      "in": "query",
      "required": true
    },
    "Signature": {
      "type": "string",
      "name": "Signature",
      "in": "query",
      "required": true
    },
    "SignatureMethod": {
      "type": "string",
      "name": "SignatureMethod",
      "in": "query",
      "required": true
    },
    "SignatureNonce": {
      "type": "string",
      "name": "SignatureNonce",
      "in": "query",
      "required": true
    },
    "SignatureVersion": {
      "type": "string",
      "name": "SignatureVersion",
      "in": "query",
      "required": true
    },
    "Timestamp": {
      "type": "string",
      "name": "Timestamp",
      "in": "query",
      "required": true
    },
    "Version": {
      "type": "string",
      "name": "Version",
      "in": "query",
      "required": true
    }
  }
}`))
}
