// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/soopsio/mgmt/api/v1/models"
)

// CreateTaskOKCode is the HTTP code returned for type CreateTaskOK
const CreateTaskOKCode int = 200

/*CreateTaskOK 返回TaskID

swagger:response createTaskOK
*/
type CreateTaskOK struct {

	/*
	  In: Body
	*/
	Payload *models.TaskState `json:"body,omitempty"`
}

// NewCreateTaskOK creates CreateTaskOK with default headers values
func NewCreateTaskOK() *CreateTaskOK {
	return &CreateTaskOK{}
}

// WithPayload adds the payload to the create task o k response
func (o *CreateTaskOK) WithPayload(payload *models.TaskState) *CreateTaskOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create task o k response
func (o *CreateTaskOK) SetPayload(payload *models.TaskState) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTaskOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateTaskDefault Unexpected error

swagger:response createTaskDefault
*/
type CreateTaskDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateTaskDefault creates CreateTaskDefault with default headers values
func NewCreateTaskDefault(code int) *CreateTaskDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateTaskDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create task default response
func (o *CreateTaskDefault) WithStatusCode(code int) *CreateTaskDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create task default response
func (o *CreateTaskDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create task default response
func (o *CreateTaskDefault) WithPayload(payload *models.Error) *CreateTaskDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create task default response
func (o *CreateTaskDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTaskDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
