// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/soopsio/mgmt/api/v1/models"
)

// GetTasksOKCode is the HTTP code returned for type GetTasksOK
const GetTasksOKCode int = 200

/*GetTasksOK 返回TaskIDs state

swagger:response getTasksOK
*/
type GetTasksOK struct {

	/*
	  In: Body
	*/
	Payload models.TaskStates `json:"body,omitempty"`
}

// NewGetTasksOK creates GetTasksOK with default headers values
func NewGetTasksOK() *GetTasksOK {
	return &GetTasksOK{}
}

// WithPayload adds the payload to the get tasks o k response
func (o *GetTasksOK) WithPayload(payload models.TaskStates) *GetTasksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tasks o k response
func (o *GetTasksOK) SetPayload(payload models.TaskStates) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTasksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.TaskStates, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetTasksDefault Unexpected error

swagger:response getTasksDefault
*/
type GetTasksDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTasksDefault creates GetTasksDefault with default headers values
func NewGetTasksDefault(code int) *GetTasksDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTasksDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get tasks default response
func (o *GetTasksDefault) WithStatusCode(code int) *GetTasksDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get tasks default response
func (o *GetTasksDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get tasks default response
func (o *GetTasksDefault) WithPayload(payload *models.Error) *GetTasksDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tasks default response
func (o *GetTasksDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTasksDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
